"""initial migration

Revision ID: 7188ae5f39a9
Revises: 
Create Date: 2026-01-29 10:53:45.401242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7188ae5f39a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dottore',
    sa.Column('matricola', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=16), nullable=False),
    sa.Column('ruolo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('matricola')
    )
    op.create_table('paziente',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=16), nullable=False),
    sa.Column('cognome', sa.String(length=16), nullable=False),
    sa.Column('data_di_nascita', sa.Date(), nullable=False),
    sa.Column('n_telefono', sa.String(length=10), nullable=False),
    sa.Column('sesso', sa.String(length=1), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('prenotazione',
    sa.Column('scopo', sa.String(length=80), nullable=False),
    sa.Column('data_richiesta_pren', sa.Date(), nullable=False),
    sa.Column('data_visita', sa.Date(), nullable=False),
    sa.Column('matricola', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['matricola'], ['dottore.matricola'], ),
    sa.ForeignKeyConstraint(['username'], ['paziente.username'], ),
    sa.PrimaryKeyConstraint('scopo', 'data_richiesta_pren', 'data_visita', 'matricola', 'username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prenotazione')
    op.drop_table('paziente')
    op.drop_table('dottore')
    # ### end Alembic commands ###
